comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
        if_not_found: success
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
        if_not_found: success
